package s.com.reddittestgalexy.domain.model

data class RedditData (
    var title: String,
    var author: String,
    var createdUtc: Long,
    var thumbnail: String?,
    var score: Int,
    var numComments: Int,
    var permalink: String,
    var id: String,
    var subreddit: String

//    var likes: Int?,
//    var approvedAtUtc: Long?,
//    var subreddit: String?,
//    var selftext: String?,
//    var authorFullname: String?,
//    var saved: Boolean?,
//    var modReasonTitle: String?,
//    var gilded: Int?,
//    var clicked: Boolean?,
//    var subredditNamePrefixed: String?,
//    var hidden: Boolean?,
//    var pwls: Int?,
//    var downs: Int?,
//    var hideScore: Boolean?,
//    var name: String?,
//    var quarantine: Boolean?,
//    var linkFlairTextColor: String?,
//    var subredditType: String?,
//    var ups: Int?,
//    var totalAwardsReceived: Int?,
//    var thumbnailWidth: Int?,
//    var thumbnailHeight: Int?,
//    var authorFlairTemplateId: String?,
//    var isOriginalContent: Boolean?,
//    var secureMedia: String?,
//    var isRedditMediaDomain: Boolean?,
//    var isMeta: Boolean?,
//    var category: String?,
//    var linkFlairText: String?,
//    var canModPost: Boolean?,
//    var approvedBy: String?,
//    var authorPremium: Boolean?,
//    var edited: Boolean?,
//    var authorFlairCssClass: String?,
//    var contentCategories: String?,
//    var isSelf: Boolean?,
//    var created: Long?,
//    var linkFlairType: String?,
//    var wls: Int?,
//    var removedByCategory: String?,
//    var bannedBy: String?,
//    var authorFlairType: String?,
//    var domain: String?,
//    var allowLiveComments: Boolean?,
//    var selftextHtml: String?,
//    var suggestedSort: String?,
//    var bannedAtUtc: Long?,
//    var viewCount: Int?,
//    var archived: Boolean?,
//    var noFollow: Boolean?,
//    var isCrosspostable: Boolean?,
//    var pinned: Boolean?,
//    var over18: Boolean?,
//    var mediaOnly: Boolean?,
//    var canGild: Boolean?,
//    var spoiler: Boolean?,
//    var locked: Boolean?,
//    var authorFlairText: String?,
//    var visited: Boolean?,
//    var removedBy: String?,
//    var numReports: Int?,
//    var distinguished: String?,
//    var subredditId: String?,
//    var modReasonBy: String?,
//    var removalReason: String?,
//    var linkFlairBackgroundColor: String?,
//    var isRobotIndexable: Boolean?,
//    var reportReasons: String?,
//    var discussionType: String?,
//    var sendReplies: Boolean?,
//    var whitelistStatus: String?,
//    var contestMode: Boolean?,
//    var authorPatreonFlair: Boolean?,
//    var authorFlairTextColor: String?,
//    var permalink: String?,
//    var parentWhitelistStatus: String?,
//    var stickied: Boolean?,
//    var url: String?,
//    var subredditSubscribers: Int?,
//    var numCrossposts: Int?,
//    var media: String?,
//    var isVideo: Boolean?
    )